### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER error

### ISSUE THREAD

**Issue by dennisrosenbaum** [Voyz/ibeam#157]
Hi - I’m looking to deploy IBeam using a Docker container and followed [this](https://github.com/Voyz/ibeam/wiki/TLS-Certificates-and-HTTPS#proprietary-tls-certificates) guide in the documentation to setup proprietary TLS certificates.  I am stuck on this error and can't figure it out.  Any ideas what may be causing this?

Appreciate any support/assistance.

Here is my environment:
IBeam version:  0.4.6
Docker image or standalone: image
Python version (standalone users only): -
OS: MacOS

Here is the conf.yaml being used as well as the full error log:
<details>
<summary>conf.yaml</summary>
ip2loc: "US"
proxyRemoteSsl: true
proxyRemoteHost: "https://api.ibkr.com"
listenPort: 5001
listenSsl: true
svcEnvironment: "v1"
sslCert: "cacert.jks"
sslPwd: "my_password"
authDelay: 3000
portalBaseURL: ""
serverOptions:
    blockedThreadCheckInterval: 1000000
    eventLoopPoolSize: 20
    workerPoolSize: 20
    maxWorkerExecuteTime: 100
    internalBlockingPoolSize: 20
cors:
    origin.allowed: "*"
    allowCredentials: false
webApps:
    - name: "demo"
      index: "index.html"
ips:
  allow:
    - 192.*
    - 131.216.*
    - 127.0.0.1
    - 0.0.0.0
    - 172.17.0.*
  deny:
    - 212.90.324.10

</details>
<details>
  <summary>error log</summary>
2023-08-09 00:50:42,855|I| ############ Starting IBeam version 0.4.6 ############
2023-08-09 00:50:42,856|I| TLS certificates found and will be used for verification
2023-08-09 00:50:42,856|I| Custom conf.yaml found and will be used by the Gateway
2023-08-09 00:50:42,859|I| Secrets source: env
2023-08-09 00:50:42,859|I| Health server started at port=5001
2023-08-09 00:50:42,859|I| Environment variable configuration:
{'INPUTS_DIR': '/srv/inputs/', 'OUTPUTS_DIR': '/srv/outputs', 'GATEWAY_DIR': '/srv/clientportal.gw', 'CHROME_DRIVER_PATH': '/usr/bin/chromedriver', 'GATEWAY_STARTUP': 20, 'GATEWAY_PROCESS_MATCH': 'ibgroup.web.core.clientportal.gw.GatewayStart', 'MAINTENANCE_INTERVAL': 60, 'SPAWN_NEW_PROCESSES': False, 'LOG_LEVEL': 'INFO', 'LOG_TO_FILE': True, 'LOG_FORMAT': '%(asctime)s|%(levelname)-.1s| %(message)s', 'REQUEST_RETRIES': 1, 'REQUEST_TIMEOUT': 15, 'RESTART_FAILED_SESSIONS': True, 'RESTART_WAIT': 15, 'REAUTHENTICATE_WAIT': 15, 'IBEAM_HEALTH_SERVER_PORT': 5001, 'GATEWAY_BASE_URL': 'https://localhost:5001', 'ROUTE_AUTH': '/sso/Login?forwardTo=22&RL=1&ip2loc=on', 'ROUTE_USER': '/v1/api/one/user', 'ROUTE_VALIDATE': '/v1/portal/sso/validate', 'ROUTE_REAUTHENTICATE': '/v1/portal/iserver/reauthenticate?force=true', 'ROUTE_AUTH_STATUS': '/v1/api/iserver/auth/status', 'ROUTE_TICKLE': '/v1/api/tickle', 'ROUTE_LOGOUT': '/v1/api/logout', 'USER_NAME_EL': None, 'PASSWORD_EL': 'password', 'SUBMIT_EL': 'button.btn.btn-lg.btn-primary', 'ERROR_EL': None, 'SUCCESS_EL_TEXT': 'Client login succeeds', 'OAUTH_TIMEOUT': 15, 'PAGE_LOAD_TIMEOUT': 15, 'ERROR_SCREENSHOTS': False, 'MAX_FAILED_AUTH': 5, 'MIN_PRESUBMIT_BUFFER': 5, 'MAX_PRESUBMIT_BUFFER': 30, 'MAX_IMMEDIATE_ATTEMPTS': 10, 'IBKEY_PROMO_EL_CLASS': 'ibkey-promo-skip', 'TWO_FA_EL_ID': 'twofactbase', 'TWO_FA_NOTIFICATION_EL': 'login-step-notification', 'TWO_FA_INPUT_EL_ID': 'chlginput', 'TWO_FA_HANDLER': None, 'STRICT_TWO_FA_CODE': True, 'TWO_FA_SELECT_EL_ID': 'sf_select', 'TWO_FA_SELECT_TARGET': 'IB Key'}
2023-08-09 00:50:42,859|I| Gateway not found, starting new one...
2023-08-09 00:50:42,860|I| Note that the Gateway log below may display "Open https://localhost:5000 to login" - ignore this command.
2023-08-09 00:50:42,860|I| Starting Gateway as Linux process with params: ['bash', 'bin/run.sh', 'root/conf.yaml']
running  
 runtime path : root:dist/ibgroup.web.core.iblink.router.clientportal.gw.jar:build/lib/runtime/*
 config file  : root/conf.yaml
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/srv/clientportal.gw/build/lib/runtime/netty-common-4.1.15.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 -> mount demo on /demo
Java Version: 11.0.18
****************************************************
version: 485dc2d762781c4ff3954ac4fb66a9469a1405f7 Mon, 20 Mar 2023 14:39:35 -0400
****************************************************
This is the Client Portal Gateway
for any issues, please contact api@ibkr.com
and include a copy of your logs
****************************************************
https://www.interactivebrokers.com/api/doc.html
****************************************************
Open https://localhost:5001 to login
App demo is available after you login under: https://localhost:5001/demo#/
Server listen failed Address already in use
2023-08-09 00:50:43,863|I| Gateway started with pid: 13
127.0.0.1 - - [09/Aug/2023 00:50:43] code 400, message Bad request version ('\\x00\\x04\\x03\\x00\\x01\\x02\\x00')
127.0.0.1 - - [09/Aug/2023 00:50:43] "\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x8c<ºÙO\x08h\x03,@²×H\x19:ÛGu\x17.¹Ï®\x0bÙrËºïË¾\x17 NGf\x91ë\x91\x7f\x16\x95\x98§ó\x0c\x1br®Ä\x1bó\x99©K¿\x90VúØ\x81-"\x05.\x00$\x13\x02\x13\x03\x13\x01À,À0À+À/Ì©Ì¨À$À(À#À'\x00\x9f\x00\x9e\x00k\x00g\x00ÿ\x01\x00\x01\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\x09localhost\x00\x0b\x00\x04\x03\x00\x01\x02\x00" 400 -
2023-08-09 00:50:43,868|E| Unrecognised URLError or socket.timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/ibeam/src/http_handler.py", line 65, in _request
    response = self.url_request(url)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/ibeam/src/http_handler.py", line 51, in url_request
    return urllib.request.urlopen(url, context=self.ssl_context, timeout=self.request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/ibeam/src/http_handler.py", line 130, in _request
    raise RuntimeError('Unrecognised URLError or socket.timeout') from e
RuntimeError: Unrecognised URLError or socket.timeout
2023-08-09 00:50:43,873|I| Gateway connection established
127.0.0.1 - - [09/Aug/2023 00:50:43] code 400, message Bad request version ('\\x00\\x04\\x03\\x00\\x01\\x02\\x00')
127.0.0.1 - - [09/Aug/2023 00:50:43] "\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03#T\x8aq/Wº1\x94\x95¿\x961åK9b\x16û&_\x16\x05·Ü\x14Ö\x8cÁ\x05Æ¢  ¼ô\x15\x10µ0¡kJ\x18÷ºd6ªöTÁC\x095\x82PÄUë4Ùã')\x00$\x13\x02\x13\x03\x13\x01À,À0À+À/Ì©Ì¨À$À(À#À'\x00\x9f\x00\x9e\x00k\x00g\x00ÿ\x01\x00\x01\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\x09localhost\x00\x0b\x00\x04\x03\x00\x01\x02\x00" 400 -
2023-08-09 00:50:43,875|E| Unrecognised URLError or socket.timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/ibeam/src/http_handler.py", line 65, in _request
    response = self.url_request(url)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/ibeam/src/http_handler.py", line 51, in url_request
    return urllib.request.urlopen(url, context=self.ssl_context, timeout=self.request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/ibeam/src/http_handler.py", line 130, in _request
    raise RuntimeError('Unrecognised URLError or socket.timeout') from e
RuntimeError: Unrecognised URLError or socket.timeout
127.0.0.1 - - [09/Aug/2023 00:50:43] code 400, message Bad request version ('\\x00\\x04\\x03\\x00\\x01\\x02\\x00')
127.0.0.1 - - [09/Aug/2023 00:50:43] "\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x85B\x82Ç\x16\x9b®;\x18¤°ñ«K»1ìQ\x9c\x9e\x9c\x8bî\x86fé!¸\x1c\x93^$ \x96¥\x8fñµ\x97d¼\x8b\x89Xê/\x07\x87á\x99(«àÌ\x85ÅúÎs\x8a(áò\x05.\x00$\x13\x02\x13\x03\x13\x01À,À0À+À/Ì©Ì¨À$À(À#À'\x00\x9f\x00\x9e\x00k\x00g\x00ÿ\x01\x00\x01\x8f\x00\x00\x00\x0e\x00\x0c\x00\x00\x09localhost\x00\x0b\x00\x04\x03\x00\x01\x02\x00" 400 -
2023-08-09 00:50:43,879|E| Unrecognised URLError or socket.timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/ibeam/src/http_handler.py", line 65, in _request
    response = self.url_request(url)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/ibeam/src/http_handler.py", line 51, in url_request
    return urllib.request.urlopen(url, context=self.ssl_context, timeout=self.request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/ibeam/src/http_handler.py", line 130, in _request
    raise RuntimeError('Unrecognised URLError or socket.timeout') from e
RuntimeError: Unrecognised URLError or socket.timeout
2023-08-09 00:50:43,885|I| No active sessions, logging in...
2023-08-09 00:50:43,885|I| Loading auth webpage at https://localhost:5001/sso/Login?forwardTo=22&RL=1&ip2loc=on
127.0.0.1 - - [09/Aug/2023 00:50:45] code 400, message Bad request version ('\\x9e\\x89\\x88\\x9f\\x81')
127.0.0.1 - - [09/Aug/2023 00:50:45] "\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x0b:ðÇ\x0f\x0d\x09 \x9e\x89\x88\x9f\x81" 400 -
127.0.0.1 - - [09/Aug/2023 00:50:45] code 400, message Bad request version ('\\x00\\x02\\x01\\x00\\x00')
127.0.0.1 - - [09/Aug/2023 00:50:45] "\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03KAiÐðzætg\x16w\x9eð[kðU'k2ÇJÀ\x1cæU0aË\x07\x98+ \x11Ò\\îÉ\x80\x96¯\x85\x8a°]èAüö\x93z\x80\x1f\\´\x14Ð¸Ûl"\x19B©1\x00 JJ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x93zz\x00\x00\x00\x05\x00\x05\x01\x00\x00\x00\x00Di\x00\x05\x00\x03\x02h2\x00-\x00\x02\x01\x01\x00\x0b\x00\x02\x01\x00\x00" 400 -
2023-08-09 00:50:45,077|E| Error encountered during authentication
Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 257, in authenticate_gateway
    driver.get(base_url + var.ROUTE_AUTH)
  File "/opt/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 449, in get
    self.execute(Command.GET, {"url": url})
  File "/opt/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/opt/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_SSL_PROTOCOL_ERROR
  (Session info: headless chrome=113.0.5672.126)
Stacktrace:
#0 0xaaaab2b38284 <unknown>
#1 0xaaaab28a5208 <unknown>
#2 0xaaaab289eebc <unknown>
#3 0xaaaab2892e00 <unknown>
#4 0xaaaab289435c <unknown>
#5 0xaaaab2893138 <unknown>
#6 0xaaaab28922d4 <unknown>
#7 0xaaaab28921c8 <unknown>
#8 0xaaaab2890cb8 <unknown>
#9 0xaaaab2891078 <unknown>
#10 0xaaaab28a7b9c <unknown>
#11 0xaaaab2914b5c <unknown>
#12 0xaaaab29145d4 <unknown>
#13 0xaaaab28cfce0 <unknown>
#14 0xaaaab28d0f6c <unknown>
#15 0xaaaab2b06884 <unknown>
#16 0xaaaab2b08e78 <unknown>
#17 0xaaaab2b089dc <unknown>
#18 0xaaaab2b0f32c <unknown>
#19 0xaaaab2b09798 <unknown>
#20 0xaaaab2ae8ff0 <unknown>
#21 0xaaaab2b22c28 <unknown>
#22 0xaaaab2b22df0 <unknown>
#23 0xaaaab2b30cf0 <unknown>
#24 0xffff83faf648 start_thread
#25 0xffff83756fdc <unknown>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 447, in authenticate_gateway
    raise RuntimeError('Error encountered during authentication') from e
RuntimeError: Error encountered during authentication
2023-08-09 00:50:45,078|I| Cleaning up the resources. Display: <pyvirtualdisplay.display.Display object at 0xffff9668cad0> | Driver: <selenium.webdriver.chrome.webdriver.WebDriver (session="de393543c39da786bbfe9cb7e188af68")>
2023-08-09 00:50:45,097|I| Authentication process failed
2023-08-09 00:50:45,099|I| Starting maintenance with interval 60 seconds

</details>

**Comment by Voyz** [comment]
Hey @dennisrosenbaum thanks for your issue report 👍 

From the log I can see that the port number has been modified:

`'GATEWAY_BASE_URL': 'https://localhost:5001'`

However, 5001 is already occupied by the health server:

`'IBEAM_HEALTH_SERVER_PORT': 5001`

Try changing the IBeam port number back to 5000 and see if that works. Alternatively, change the health server port to something else.

Let me know if it helps.

**Comment by dennisrosenbaum** [comment]
Thanks so much! I did modify the port as 5000 was already in use by default on my Mac.  I changed the IBEAM_HEALTH_SERVER_PORT to 5008 and am able to successfully authenticate and run the gateway.

One question - is there any documentation around the maintenance being performed when the gateway is running?  Just wondering what's happening during that time.

Thanks again for the support!  Greatly appreciated.

**Comment by Voyz** [comment]
Well done 🥳

Yes, maintenance will simply check if we're authenticated, and if not it will log in. Both starting and maintenance do pretty much the same thing - maintenance just does it after a successful start on a regular interval.

See here: https://github.com/Voyz/ibeam#how-does-ibeam-work

**Comment by dennisrosenbaum** [comment]
You're a legend. Thanks for fielding the questions and sharing your project with all of us...really cool stuff!  Can't wait to dive in further and learn more.

Thanks again!

**Comment by Voyz** [comment]
Hey no worries and thanks for the kind words 😊

Feel free to close this issue if you think we've answered your questions 👍
