### ISSUE TITLE
Invalid username password combination

### ISSUE THREAD

**Issue by heymarkmckay** [Voyz/ibeam#21]
**Describe the bug**
I receive the error message "Invalid username password combination" on the https://localhost:5000 login screen. My username and password are correct, and I receive a text message with my authentication code from Interactive Brokers. 

**To Reproduce**
1. From terminal, run "docker run --env-file env.list -p 5000:5000 voyz/ibeam"
2. Open "https://localhost:5000" in browser
3. Enter username and password
4. See error in red box below login in button

<img width="1475" alt="Screen Shot 2021-05-25 at 2 47 21 PM" src="https://user-images.githubusercontent.com/10703210/119555099-73fc5880-bd6b-11eb-92a7-92569c06d975.png">

**Expected behavior**
From the video tutorial I am following, I expect to see the security code box pop-up so I can enter the 2FA code

**Environment**

I am using the setup from "docker pull voyz/ibeam"

IBeam version: is this set by docker? how do I tell?
Python version: is this set by docker? how do I tell? 
OS: MacOS 11.3.1

**Additional context**

- I can log into my account from the browser, TWS and IB Gateway without any problems, so I do not think it is my username and password.
- I thought there might be an issue with my password starting with !, after I ran into an issue running the docker image with the username and password, instead of using the env file. I changed my password, and I am still having the same issue. 
- It seems that the issue is that the localhost login page thinks that my username and password combination is invalid, but I can confirm that it is not. 

**Terminal Log**

<

markmckay@Marks-MBP ibeam-test % docker run --env-file env.list -p 5000:5000 voyz/ibeam
2021-05-25 19:08:00,351|I| Gateway not found, starting new one...
running  
 runtime path : root:dist/ibgroup.web.core.iblink.router.clientportal.gw.jar:build/lib/runtime/*
 verticle     : 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/srv/clientportal.gw/build/lib/runtime/netty-common-4.1.15.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
 -> mount demo on /demo
Java Version: 11.0.8
****************************************************
version: ed4af2592e9dd4a784d5403843bd18292fd441ea Fri, 9 Nov 2018 13:23:18 -0500
****************************************************
This is a Beta release of the Client Portal Gateway
for any issues, please contact api@ibkr.com
and include a copy of your logs
****************************************************
https://www.interactivebrokers.com/api/doc.html
****************************************************
Open https://localhost:5000 to login
App demo is available after you login under: https://localhost:5000/demo/
2021-05-25 19:08:03,358|I| Gateway started with pid: 13
2021-05-25 19:08:03,939|I| No active sessions, logging in...
2021-05-25 19:08:22,332|E| Error encountered during authentication
Traceback (most recent call last):
  File "/srv/ibeam/src/gateway_client.py", line 176, in authenticate_gateway
    WebDriverWait(driver, _OAUTH_TIMEOUT).until(success_present)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/ibeam/src/gateway_client.py", line 183, in authenticate_gateway
    raise RuntimeError('Error encountered during authentication') from e
RuntimeError: Error encountered during authentication
2021-05-25 19:08:22,340|I| Login failed
2021-05-25 19:08:22,671|I| Starting maintenance with interval 60 seconds

>

**Comment by Voyz** [comment]
Hey @heymarkmckay welcome to IBeam and thanks for submitting the issue! 👋

I just want to first say: This is a fantastic issue report, you provided so much great detail - thanks for doing that!

However, I'm sorry to say that this is a known issue with IBKR Client Portal Web API. If you search through the history of PR #12 you'll see a number of users running into this. We've been highlighting this to IBKR but so far there hasn't been any improvement made. I'd suggest you submit a support ticket to IBKR to underline the importance of this issue. In the meantime you can try out the `0.3.0-*` image as it has some logic introduced to minimise the impact of this issue.

I'm really sorry I cannot be of more help - especially that you've really put great effort into describing this problem - but at the time there's little we can do from our perspective other than to report the problem to IBKR.

**Comment by Voyz** [comment]
Also just to clarify:

> IBeam version: is this set by docker? how do I tell?

This would be whatever IBeam image you're using. If none is specified, I'd probably say 'latest'.

> Python version: is this set by docker? how do I tell?

IBeam can be used as standalone, without a Docker container, in which case you'd probably be aware of this value. 

----

I appreciate you writing this, as it highlights it may be a good idea to rephrase the issue template 👍

**Comment by Voyz** [comment]
I've updated the the GitHub Issue template to reflect the doubts you have in this issue - thanks for outlining them 👍

I'm closing this issue due to inactivity - feel free to open it again if you'd like to continue. Thanks! 👋

**Comment by heymarkmckay** [comment]
@Voyz thanks so much for your hep and for the feedback on my bug report. Unfortunately I wasn't able to make this work and gave up. I really appreciate your help and for making this available on Github. All my best!

**Comment by dgmstevenson** [comment]
I had the exact same problem and was able to solve it by removing all symbols from my password.

**Comment by Voyz** [comment]
That's an interesting theory @dgmstevenson thanks for sharing it 👍 @heymarkmckay if you don't mind sharing this, did your password contain symbols and special characters?

**Comment by edwardsun** [comment]
> I had the exact same problem and was able to solve it by removing all symbols from my password.

Thanks for the hint. I removed <$> symbol in my passwords (now only containing alphanumrics) and got it to work.
