### ISSUE TITLE
 Error encountered during authentication

### ISSUE THREAD

**Issue by zanek** [Voyz/ibeam#23]
I ran the command prompt as Administrator

I'm getting this error:  

2021-07-01 18:20:56,543|E| Error encountered during authentication
Traceback (most recent call last):
  File "C:\Users\pps\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\pps\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\pps\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pps\Documents\multi\ibeam-master\ibeam-master\ibeam\src\authenticate.py", line 151, in authenticate_gateway
    driver = start_driver(base_url, driver_path)
  File "C:\Users\pps\Documents\multi\ibeam-master\ibeam-master\ibeam\src\authenticate.py", line 286, in start_driver
    raise e
  File "C:\Users\pps\Documents\multi\ibeam-master\ibeam-master\ibeam\src\authenticate.py", line 274, in start_driver
    driver = new_chrome_driver(driver_path)
  File "C:\Users\pps\Documents\multi\ibeam-master\ibeam-master\ibeam\src\authenticate.py", line 48, in new_chrome_driver
    driver = webdriver.Chrome(driver_path, options=options)
  File "C:\Users\pps\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\pps\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_win32' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pps\Documents\multi\ibeam-master\ibeam-master\ibeam\src\authenticate.py", line 254, in authenticate_gateway
    raise RuntimeError('Error encountered during authentication') from e
RuntimeError: Error encountered during authentication

**To Reproduce**
1. Logged into the IB Client Gateway
2.  py ibeam_starter.py -m
3. Wait 3 hours

**Expected behavior**
renew authentication

**Environment**
IBeam version: latest
Docker image or standalone: standalone
Python version (standalone users only): 3.7
OS: Windows 10

**Comment by Voyz** [comment]
Hi @zanek welcome to IBeam and thanks for your issue report! 👋

So you're saying that for some 3 hours things are working fine, but eventually this error appears? Or does it appear right from the beginning?

**Comment by zanek** [comment]
If I dont use IBeam, I can call the Tickle API endpoint every minute and I wont get the Unauthorized error until 3 hours. My hope was that I could use IBeam to keep the API open beyond 3 hours, but it gives me that error at the 3 hour mark.

Have you used IBeam to leave the API open for a day ?

**Comment by Voyz** [comment]
Thanks for clarifying @zanek So you see this error after 3 hours even when you don't use IBeam? If I understood you correctly, then I would say this sounds a lot more like an issue with IBKR than IBeam. Did you try contacting their support team in that regard?

**Comment by Voyz** [comment]
Hi @zanek - I'm going to close this issue due to lack of activity. Feel free to reopen it if you'd like to resume the discussion. Thank you for contributing in either case!
