### ISSUE TITLE
Could not run Docker to login to IB

### ISSUE THREAD

**Issue by VincenLiu4587** [Voyz/ibeam#35]
**Describe the bug**
[root@ip-172-31-25-105 ~]# docker run --env-file env.list -p 5000:5000 voyz/ibeam
2021-10-09 23:52:21,414|I| ############ Starting IBeam version 0.3.0 ############
Account: Traceback (most recent call last):
  File "ibeam_starter.py", line 63, in <module>
    driver_path=driver_path)
  File "/srv/ibeam/src/gateway_client.py", line 55, in __init__
    self.account = input('Account: ')
EOFError: EOF when reading a line
2021-10-09 23:52:21,817|I| ############ Starting IBeam version 0.3.0 ############
Account: Traceback (most recent call last):
  File "ibeam_starter.py", line 63, in <module>
    driver_path=driver_path)
  File "/srv/ibeam/src/gateway_client.py", line 55, in __init__
    self.account = input('Account: ')
EOFError: EOF when reading a line

**Expected behavior**
user can login.

**Environment**
IBeam version: 0.3.0
Docker image or standalone: Docker image
Python version (standalone users only):
OS: Linux

**Additional context**
No

**Comment by VincenLiu4587** [comment]
[root@ip-172-31-25-105 inputs]# pwd
/root/inputs
[root@ip-172-31-25-105 inputs]# ls -l
total 4
-rw-r--r-- 1 root root 619 Oct  9 23:38 conf.yaml
[root@ip-172-31-25-105 inputs]# cd ..
[root@ip-172-31-25-105 ~]# ls -l
total 4
-rw-r--r-- 1 root root 48 Oct  9 23:27 env.list
drwxr-xr-x 2 root root 23 Oct  9 23:38 inputs


I already created the inputs folder and conf.yaml

**Comment by VincenLiu4587** [comment]
false alarm, sorry

**Comment by Voyz** [comment]
Hey @VincenLiu4587 No worries, glad you could figure it out after all 😊
