### ISSUE TITLE
Docker process crashing when starting ibeam with external conf.yaml

### ISSUE THREAD

**Issue by sanjinbecirovic** [Voyz/ibeam#51]
![image](https://user-images.githubusercontent.com/7047868/149558771-389807b6-8fdb-4adb-a180-7006b2adfa09.png)

The only change is an IP address addition to conf.yaml

**Comment by JohnLiz** [comment]
@sanjinbecirovic I believe we're both having the same problem, what's weird is that it happened all of a sudden 6 days ago.

Did you make an update to your chrome browser recently? Im just trying to pin point the issue here.

`
2022-01-14 21:41:38,156|E| Error encountered during authentication
Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 232, in authenticate_gateway
    two_fa_el[0].send_keys(two_fa_code)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=96.0.4664.110)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 277, in authenticate_gateway
    raise RuntimeError('Error encountered during authentication') from e
RuntimeError: Error encountered during authentication
2022-01-14 21:41:38,225|I| Authentication process failed
2022-01-14 21:41:38,565|I| ############ Starting IBeam version 0.3.0 ############
`

**Comment by Voyz** [comment]
Hey @sanjinbecirovic and @JohnLiz thanks for sharing your error reports. Could I ask you to provide a bit extra info on your setup? Please fill out [the template of the new bug issue](https://github.com/Voyz/ibeam/issues/new?assignees=&labels=bug&template=bug_report.md&title=).

Also, @sanjinbecirovic what makes you think it's setting the `conf.yaml` that causes this problem? The error seems to appear when selenium tries to connect to Chrome, which isn't affected by the custom IPs specified in the `conf.yaml`. Can you provide [debug logs](https://github.com/Voyz/ibeam/wiki/IBeam-Configuration#debugging) when running both with a custom and with the default `conf.yaml`?

**Comment by sanjinbecirovic** [comment]
@Voyz @JohnLiz I had to add a local disk to the GCP VM as it can be depicted in the screenshot. 0.4.0-rc5 works nicely!
![image](https://user-images.githubusercontent.com/7047868/151695478-7ea7e834-72a2-43e2-b3f1-991bdf0396bd.png)

**Comment by Voyz** [comment]
Thanks for following up @sanjinbecirovic 👍 I cannot see at all why adding a local disk would help here. Could you confirm that removing that disk would recreate the issue you were experiencing?
