### ISSUE TITLE
Selenium fails to connect to Chrome and fails

### ISSUE THREAD

**Issue by JohnLiz** [Voyz/ibeam#52]
Per your request @Voyz I have created a bug report with the new template.

**Describe the bug**
Whenever i attempt to startup iBeam, and send the auth key to IBKR it fails. I believe its failing at the the `two_fa_el[0].send_keys(two_fa_code)` step.

```
2022-01-14 21:41:38,156|E| Error encountered during authentication
Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 232, in authenticate_gateway
    two_fa_el[0].send_keys(two_fa_code)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 479, in send_keys
    'value': keys_to_typing(value)})
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=96.0.4664.110)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/srv/ibeam/src/authenticate.py", line 277, in authenticate_gateway
    raise RuntimeError('Error encountered during authentication') from e
RuntimeError: Error encountered during authentication
2022-01-14 21:41:38,225|I| Authentication process failed
2022-01-14 21:41:38,565|I| ############ Starting IBeam version 0.3.0 ############
```

**To Reproduce**
1. Start up docker run
2. Auth by passing the auth code
3. Fails
4. 

**Expected behavior**
Auth process should pass with the following message `Gateway running and authenticated`

**Environment**
IBeam version: **0.3.0**
Docker image or standalone: **Docker Image**
Python version (standalone users only): **Python 3.9.2**
OS: **Windows/Linux**

**Comment by Voyz** [comment]
Thanks for the detailed issue report @JohnLiz 👍 I'm not entirely sure which way to go from here, so just to see if it helps: could you try running the `v0.4.0-rc5` image to see if the issue persists in 0.4.0 version?

**Comment by JohnLiz** [comment]
@Voyz  I had tried 4.0 same issue. If an update to a desktop chrome be the cause of it? I had recently updated my chrome browser and suspecting its the problem. Doesn't iBeam use the user chrome to built the chromium when using something like docker build?

**Comment by Voyz** [comment]
Sorry for a delay @JohnLiz, I was on holiday past couple of weeks.  

>  I had tried 4.0 same issue.

Thanks, that's useful to know.

> If an update to a desktop chrome be the cause of it?
> Doesn't iBeam use the user chrome to built the chromium when using something like docker build?

I don't think so. Chromium is part of the IBeam image, your local version makes no difference here.

That being said, are you building an IBeam Docker image yourself?

**Comment by Voyz** [comment]
Hey @JohnLiz I'm going to close this issue due to lack of activity. Feel free to reopen it if you'd like to continue the discussion 👍
